from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from .database import Bot, User, get_db
from .docker_manager import DockerManager

router = APIRouter(prefix="/bots", tags=["bots"])
docker = DockerManager()
BOTS_ROOT = Path("user_bots")
TEMPLATE_BOT = BOTS_ROOT / "templates" / "bot.py"


class BotCreatePayload(BaseModel):
    owner_id: int
    name: str
    source_code: str


class BotActionPayload(BaseModel):
    owner_id: int


def _require_bot_owner(db: Session, bot_id: int, owner_id: int) -> Bot:
    bot = db.query(Bot).filter(Bot.id == bot_id, Bot.owner_id == owner_id).first()
    if not bot:
        raise HTTPException(status_code=404, detail="Bot not found")
    return bot


@router.post("/")
def create_bot(payload: BotCreatePayload, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.id == payload.owner_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="Owner not found")

    normalized_name = payload.name.strip() or "unnamed-bot"
    source_code = payload.source_code.strip()
    if not source_code and TEMPLATE_BOT.exists():
        source_code = TEMPLATE_BOT.read_text(encoding="utf-8")
    elif not source_code:
        source_code = 'print("Hello from hosted bot")'

    bot = Bot(name=normalized_name, owner_id=payload.owner_id, source_code=source_code)
    db.add(bot)
    db.commit()
    db.refresh(bot)

    bot_dir = BOTS_ROOT / f"user{payload.owner_id}" / f"bot{bot.id}"
    bot_dir.mkdir(parents=True, exist_ok=True)
    (bot_dir / "bot.py").write_text(source_code, encoding="utf-8")
    (bot_dir / "README.txt").write_text(
        "Bot generated by lrrhub\nOwner rights: l19r\n",
        encoding="utf-8",
    )

    return {"message": "Bot created", "bot_id": bot.id}


@router.post("/{bot_id}/start")
def start_bot(bot_id: int, payload: BotActionPayload, db: Session = Depends(get_db)):
    bot = _require_bot_owner(db, bot_id, payload.owner_id)
    if bot.is_running:
        return {"message": "Bot is already running", "container_id": bot.container_id}

    bot_dir = BOTS_ROOT / f"user{payload.owner_id}" / f"bot{bot.id}"
    if not (bot_dir / "bot.py").exists():
        raise HTTPException(status_code=400, detail="Bot source file missing")

    try:
        container_id = docker.run_bot(bot_dir)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to start bot: {exc}") from exc

    bot.is_running = True
    bot.container_id = container_id
    db.commit()

    return {"message": "Bot started", "container_id": container_id}


@router.post("/{bot_id}/stop")
def stop_bot(bot_id: int, payload: BotActionPayload, db: Session = Depends(get_db)):
    bot = _require_bot_owner(db, bot_id, payload.owner_id)
    if not bot.is_running or not bot.container_id:
        return {"message": "Bot is already stopped"}

    try:
        docker.stop_bot(bot.container_id)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to stop bot: {exc}") from exc

    bot.is_running = False
    bot.container_id = None
    db.commit()
    return {"message": "Bot stopped"}


@router.get("/{bot_id}/logs")
def get_logs(bot_id: int, owner_id: int, db: Session = Depends(get_db)):
    bot = _require_bot_owner(db, bot_id, owner_id)
    if not bot.container_id:
        raise HTTPException(status_code=400, detail="Bot has no running container")

    try:
        logs = docker.get_logs(bot.container_id)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to fetch logs: {exc}") from exc

    return {"bot_id": bot.id, "logs": logs}
